require("plugins.tokyonight")
require("plugins.mini-icons")
require("plugins.oil-nvim")
require("plugins.oil-git-nvim")
require("plugins.oil-lsp-diagnostics-nvim")
require("plugins.mini-pick")
require("plugins.nvim-lspconfig")
require("plugins.mason-nvim")
