require("plugins.tokyonight")
require("plugins.nvim-lspconfig")
-- require("plugins.mason")
-- require("plugins.mason-lspconfig")
-- require("plugins.mason-tool-installer")
require("plugins.telescope-nvim")
require("plugins.yazi")
require("plugins.neo-tree")
require("plugins.nvim-tmux-navigator")
require("plugins.nvim-surround")
require("plugins.nvim-treesitter")
require("plugins.lualine")
require("plugins.blink-cmp")
require("plugins.tiny-inline-diagnostics")
require("plugins.tiny-code-actions")
require("plugins.gitsigns")
require("plugins.neoscroll")
require("plugins.dressing")
require("plugins.smear-cursor")
require("plugins.pack-manager")
require("plugins.comment")
require("plugins.nvim-ts-autotag")
require("plugins.emmet-vim")
require("plugins.indentscope")
