require("plugins.tokyonight")
require("plugins.nvim-lspconfig")
require("plugins.mason-nvim")
require("plugins.telescope-nvim")
require("plugins.yazi-nvim")
require("plugins.neotree")
require("plugins.nvim-tmuxnavigator")
require("plugins.nvim-surround")
